# Internationalization User Guide
# https://docs.google.com/document/d/10e0saTfAv32OZLRmONy866vnaw0I2jwL8zukykpgWBc/edit#

# arb文件目录
arb-dir: lib/intl/l10n

# 模板文件
template-arb-file: intl_zh.arb

# 指定本地化文件输出路径, 如果要配置此项需将[synthetic-package] 设置为false
output-dir: lib/intl

# 输出文件名称
output-localization-file: app_localizations.dart

# 输出localizations类的名称
#output-class: AppLocalizations

# 未翻译的键输出到指定文件, {root}/desiredFileName.txt
untranslated-messages-file: desiredFileName.txt

# 首选语言, 会排在supportedLocales的第一个
# 不配置此属性时, [template-arb-file]的文件默认为首选语言
preferred-supported-locales:
  - zh

# 延迟加载
# 是否生成带有作为延迟导入的语言环境的 Dart 本地化文件，允许在 Flutter web.xml 中延迟加载每个语言环境。
#use-deferred-loading: false

# 当arb文件中没有指定翻译,是否返回null
# 如果为false, 会使用首选语言的值来返回
# 如果为true, 会返回null
#nullable-getter: false

# 指定是否时合成包
# 当值为true,则生成文件在.dart_tool/flutter_gen/gen_l10n
# 当值为false, 这生成的文件在[arb-dir]目录下
synthetic-package: false

# 附加到生成的 Dart 本地化文件的头部, String类型
#header: ''

# 附加到生成的 Dart 本地化文件的头部, 文件类型, 可以得到一个更长的头部
#header-file:
  