name: yuro
description: Yuro package.
version: 0.5.0
homepage: https://github.com/YuroLtd/yuro.git

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  path: ^1.8.1
  hive_flutter: ^1.1.0          # https://pub.flutter-io.cn/packages/hive_flutter
  shared_preferences: ^2.0.15   # https://pub.dev/packages/shared_preferences
  path_provider: ^2.0.11        # https://pub.dev/packages/path_provider
  convert: ^3.0.1               # https://pub.dev/packages/convert
  crypto: ^3.0.2                # https://pub.dev/packages/crypto
  uuid: 3.0.6
  stack_trace: ^1.10.0
  dio: ^4.0.6                   # https://pub.dev/packages/dio
  mqtt_client: ^9.6.8           # https://pub.dev/packages/mqtt_client
  equatable: ^2.0.3             # https://pub.dev/packages/equatable
  buffer: ^1.1.1                # https://pub.dev/packages/buffer
  crclib: ^3.0.0                # https://pub.dev/packages/crclib

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  hive_generator: ^1.1.2      # https://pub.flutter-io.cn/packages/hive_generator

