name: yuro
description: A Flutter package.
version: 0.2.0
homepage: https://github.com/YuroLtd/yuro_kit.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^5.0.0
  path_provider: ^2.0.2
  package_info: ^2.0.0
  collection: ^1.15.0
  synchronized: ^3.0.0
  shared_preferences: ^2.0.6

  dio: ^4.0.0

  uuid: ^3.0.4
  crypto: ^3.0.1
  convert: ^3.0.0
  logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
