name: yuro
description: Yuro package.
version: 1.0.1
homepage: https://github.com/YuroLtd/yuro

environment:
  sdk: '>=2.19.3 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.17.0
  path: ^1.8.1
  isar: ^3.0.5                  # https://pub.flutter-io.cn/packages/isar
  isar_flutter_libs: ^3.0.5
  shared_preferences: ^2.0.18   # https://pub.dev/packages/shared_preferences
  path_provider: ^2.0.11        # https://pub.dev/packages/path_provider
  convert: ^3.0.1               # https://pub.dev/packages/convert
  crypto: ^3.0.2                # https://pub.dev/packages/crypto
  uuid: ^3.0.6
  dio: ^5.1.0                   # https://pub.dev/packages/dio
  equatable: ^2.0.3             # https://pub.dev/packages/equatable
  buffer: ^1.1.1                # https://pub.dev/packages/buffer
  crclib: ^3.0.0                # https://pub.dev/packages/crclib
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  isar_generator: ^3.0.5      # https://pub.flutter-io.cn/packages/isar_generator

