name: yuro
description: A Flutter package.
version: 0.4.2
publish_to: https://pub.dev/
homepage: https://github.com/YuroLtd/yuro_kit.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dio: ^4.0.4                   # https://pub.dev/packages/dio
  uuid: ^3.0.5                  # https://pub.dev/packages/uuid
  crypto: ^3.0.1                # https://pub.dev/packages/crypto
  convert: ^3.0.1               # https://pub.dev/packages/convert
  collection: ^1.15.0           # https://pub.dev/packages/collection
  synchronized: ^3.0.0          # https://pub.dev/packages/synchronized
  provider: ^6.0.1              # https://pub.dev/packages/provider
  path: ^1.8.0
  path_provider: ^2.0.8         # https://pub.dev/packages/path_provider
  shared_preferences: ^2.0.11   # https://pub.dev/packages/shared_preferences
  permission_handler: ^8.1.6    # https://pub.dev/packages/permission_handler
  equatable: ^2.0.3             # https://pub.flutter-io.cn/packages/equatable
  json_annotation: ^4.4.0       # https://pub.flutter-io.cn/packages/json_annotation
  hive: ^2.0.5                  # https://pub.flutter-io.cn/packages/hive
  hive_flutter: ^1.1.0          # https://pub.flutter-io.cn/packages/hive_flutter
  yuro_plugin: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  hive_generator: ^1.1.1      # https://pub.flutter-io.cn/packages/hive_generator/install
  json_serializable: ^6.1.3