name: yuro
description: A new Flutter project.
version: 2.0.0
homepage: https://github.com/YuroLtd/yuro

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  go_router: ^10.0.0
  shared_preferences: ^2.2.0
  path: ^1.8.3
  path_provider: ^2.0.15
  logging: ^1.1.1
  convert: ^3.1.1 
  crypto: ^3.0.3 
  uuid: ^3.0.7
  crclib: ^3.0.0 
  intl: ^0.18.0
  collection: ^1.17.1
  equatable: ^2.0.5
  isar: ^3.1.0                 
  isar_flutter_libs: ^3.1.0
  dio: ^5.3.1
  buffer: ^1.2.0
  flutter_animate: ^4.2.0

dependency_overrides:
  intl: ^0.18.1
  collection: ^1.18.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  isar_generator: ^3.1.0

