name: yuro
description: A Flutter package.
version: 0.4.0
homepage: https://github.com/YuroLtd/yuro_kit.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dio: ^4.0.0                   # https://pub.dev/packages/dio
  uuid: ^3.0.4                  # https://pub.dev/packages/uuid
  crypto: ^3.0.1                # https://pub.dev/packages/crypto
  convert: ^3.0.1               # https://pub.dev/packages/convert
  collection: ^1.15.0           # https://pub.dev/packages/collection
  synchronized: ^3.0.0          # https://pub.dev/packages/synchronized
  provider: ^6.0.0              # https://pub.dev/packages/provider
  path_provider: ^2.0.3         # https://pub.dev/packages/path_provider
  shared_preferences: ^2.0.7    # https://pub.dev/packages/shared_preferences
  permission_handler: ^8.1.6    # https://pub.dev/packages/permission_handler
  equatable: ^2.0.3             # https://pub.flutter-io.cn/packages/equatable

  yuro_plugin: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
